// Library packages are those packages that we use inside our modules and files, like Axios....
// import axios from 'axios';


// CLI packages are those packages that we use in our terminal or command line interface, like Vite, Nodemon, Express Generator, etc....

// Note: but there can be some exceptions like a package can be used from both CLI and Library............

// Local Packages are those packages that are installed and used within a specific directory or project,
// they are present inside nodemodules only.................

// Global packages can be imported or used from any directory or in any project because they installed globally on the system.............
