
// "axios": "^1.16.0" 


// 1 is Major Version, 16 is Minor Version and 0 is Patch Version...........

// Whenever we install any package nodejs will come to package.json file, then install the version mentioned there, but we need to remember few things:
// 1. If we have ^ Carrot Sybmol in the version then it will install the Minor and Patch both versions if available for a package
// (exception for those version which starts from 0, there it will work as a ~ symbol)........... 
// 2. If we have ~ Tilde Symbol in the version then it will install only Patch version if available for a package...........
// 3. If we have no symbol in the version then it will install only that version which is mentioned in the package.json file...........
// 4. If we have only * in the version then it will install the latest version of that package...........
// 5. If we have no version mentioned in the package.json file then it will install the latest version of that package...........

// Note:- If package-lock.json file is present with a locked version of a package, then it doesn't matter if we have ^, ~, * or no symbol in the version, 
// it will always install the version which is mentioned in the package-lock.json file because it has higher priority than package.json file...........